// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var App;

  App = angular.module('app', ['ngCookies', 'ngResource', 'ngRoute', 'app.controllers', 'app.directives', 'app.filters', 'app.services', 'partials', 'restangular', 'ui.bootstrap']);

  App.config([
    '$routeProvider', '$locationProvider', 'RestangularProvider', '$httpProvider', function($routeProvider, $locationProvider, RestangularProvider, $httpProvider, config) {
      var spinnerFunction;
      RestangularProvider.setBaseUrl("/api");
      $routeProvider.when('/Dashboard', {
        templateUrl: '/partials/Dashboard.html',
        controller: 'DashboardCtrl'
      }).when('/Dashboard/Events/:eventID', {
        templateUrl: '/partials/Event.html',
        controller: 'EventCtrl'
      }).when('/Settings', {
        templateUrl: '/partials/User.html',
        controller: 'UserCtrl'
      }).when('/Admin', {
        templateUrl: '/partials/AdminDashboard.html',
        controller: 'AdminDashboardCtrl'
      }).otherwise({
        redirectTo: '/Dashboard'
      });
      $locationProvider.html5Mode(false);
      $httpProvider.responseInterceptors.push("myHttpInterceptor");
      spinnerFunction = function(data, headers) {
        $("#loading").show();
        return data;
      };
      return $httpProvider.defaults.transformRequest.push(spinnerFunction);
    }
  ]);

}).call(this);

//# sourceMappingURL=app.map
