// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /* Sevices */
  angular.module('app.services', []).factory('myHttpInterceptor', [
    '$q', '$window', function($q, $window) {
      return function(promise) {
        return promise.then(function(response) {
          $('#loading').hide();
          return response;
        }, function(response) {
          $('#loading').hide();
          return $q.reject(response);
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=services.map
