// Generated by CoffeeScript 1.7.1
(function() {
  exports.config = {
    conventions: {
      assets: /^app\/assets\//,
      ignored: /^(bower_components\/bootstrap-less(-themes)?|app\/styles\/overrides|(.*?\/)?[_]\w*)/
    },
    modules: {
      definition: false,
      wrapper: false
    },
    paths: {
      "public": '../'
    },
    files: {
      javascripts: {
        joinTo: {
          'js/app.js': /^app/,
          'js/vendor.js': /^(bower_components|vendor)/
        }
      },
      stylesheets: {
        joinTo: {
          'css/app.css': /^(app|vendor|bower_components)/
        },
        order: {
          before: ['app/styles/app.less']
        }
      },
      templates: {
        joinTo: {
          'js/dontUseMe': /^app/
        }
      }
    },
    plugins: {
      jade: {
        pretty: true
      },
      jade_angular: {
        modules_folder: 'partials',
        locals: {}
      }
    }
  };

}).call(this);

//# sourceMappingURL=config.map
